ALTER TABLE users
    ADD COLUMN IF NOT EXISTS firstName VARCHAR(32);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS lastName VARCHAR(32);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS dateOfBirth TIMESTAMP;